-- Instructors Export
-- Generated: 2026-01-13T14:44:40.300Z
-- Columns matched to production schema

INSERT INTO instructors (id, user_id, first_name, last_name, email, phone, license_number, specializations, status, hire_date, account_status) VALUES
(19, NULL, 'TestInstr9wSA', 'E2EDebug', 'debug.instructor@mortys.com', '(555) 111-2222', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2023-01-01', 'pending_invite'),
(3, NULL, 'Sarah', 'Williams', 'sarah.williams@mortys.com', '(604) 555-1002', NULL, 'Motorcycle, Class 6', 'active', NULL, 'pending_invite'),
(5, NULL, 'Jennifer', 'Garcia', 'jennifer.garcia@mortys.com', '(604) 555-1004', NULL, 'Auto, Senior Training', 'active', NULL, 'pending_invite'),
(1, NULL, 'Test', 'TEst', 'test@test.com', '5141234567', NULL, '["auto","scooter"]', 'active', NULL, 'pending_invite'),
(22, NULL, 'Test', 'Instructor', 'test.instructor@example.com', '555-9876', NULL, NULL, 'active', NULL, 'pending_invite'),
(27, NULL, 'Test', 'Instructor2', 'test2@example.com', '555-1234', NULL, NULL, 'active', NULL, 'pending_invite'),
(4, NULL, 'David', 'Brown', 'david.brown@mortys.com', '(604) 555-1003', NULL, 'Auto, Defensive Driving', 'active', NULL, 'pending_invite'),
(6, NULL, 'Robert', 'Martinez', 'robert.martinez@mortys.com', '(604) 555-1005', NULL, 'Motorcycle, Scooter', 'active', NULL, 'pending_invite'),
(7, NULL, 'Lisa', 'Anderson', 'lisa.anderson@mortys.com', '(604) 555-1006', NULL, 'Auto, Commercial', 'active', NULL, 'pending_invite'),
(20, NULL, 'Marshal', 'Johnsan', 'johnson@mdatazone.com', '', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2025-10-24', 'pending_invite'),
(17, NULL, 'Mike', 'Jones', 'mike@mortys.ca', '', NULL, NULL, 'active', '', 'pending_invite'),
(29, NULL, 'Demo', 'Instructor', 'demo.instructor@example.com', '555-0100', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2024-01-01', 'pending_invite'),
(30, NULL, 'Mary', 'Rivera', 'mary.rivera0@mortys.com', '(514) 555-3000', NULL, '{"auto":{"theory":false,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2024-12-15', 'pending_invite'),
(31, NULL, 'Ronald', 'Wright', 'ronald.wright1@mortys.com', '(514) 555-3001', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":false,"practical":false}}', 'active', '2025-01-26', 'pending_invite'),
(32, NULL, 'Mark', 'Gonzalez', 'mark.gonzalez2@mortys.com', '(514) 555-3002', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2025-04-30', 'pending_invite'),
(33, NULL, 'Margaret', 'Green', 'margaret.green3@mortys.com', '(514) 555-3003', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2024-12-18', 'pending_invite'),
(34, NULL, 'Steven', 'Hernandez', 'steven.hernandez4@mortys.com', '(514) 555-3004', NULL, '{"auto":{"theory":false,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":false}}', 'active', '2025-01-31', 'pending_invite'),
(35, NULL, 'Robert', 'Lopez', 'robert.lopez5@mortys.com', '(514) 555-3005', NULL, '{"auto":{"theory":true,"practical":false},"moto":{"theory":false,"practical":false}}', 'active', '2025-05-20', 'pending_invite'),
(36, NULL, 'Melissa', 'Scott', 'melissa.scott6@mortys.com', '(514) 555-3006', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2025-05-09', 'pending_invite'),
(37, NULL, 'James', 'Wright', 'james.wright7@mortys.com', '(514) 555-3007', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2025-01-12', 'pending_invite'),
(38, NULL, 'Matthew', 'Robinson', 'matthew.robinson8@mortys.com', '(514) 555-3008', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":false,"practical":true},"scooter":{"theory":false,"practical":true}}', 'active', '2025-04-12', 'pending_invite'),
(39, NULL, 'Jacob', 'Allen', 'jacob.allen9@mortys.com', '(514) 555-3009', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2025-04-13', 'pending_invite'),
(40, NULL, 'Melissa', 'King', 'melissa.king10@mortys.com', '(514) 555-3010', NULL, '{"auto":{"theory":false,"practical":true},"moto":{"theory":false,"practical":true}}', 'active', '2025-04-30', 'pending_invite'),
(41, NULL, 'Robert', 'Baker', 'robert.baker11@mortys.com', '(514) 555-3011', NULL, '{"auto":{"theory":false,"practical":true}}', 'active', '2025-03-29', 'pending_invite'),
(42, NULL, 'Sharon', 'Davis', 'sharon.davis12@mortys.com', '(514) 555-3012', NULL, '{"auto":{"theory":true,"practical":false}}', 'active', '2025-01-28', 'pending_invite'),
(43, NULL, 'Susan', 'Flores', 'susan.flores13@mortys.com', '(514) 555-3013', NULL, '{"auto":{"theory":false,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2025-01-18', 'pending_invite'),
(44, NULL, 'Linda', 'Johnson', 'linda.johnson14@mortys.com', '(514) 555-3014', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2025-05-21', 'pending_invite'),
(45, NULL, 'Timothy', 'Wright', 'timothy.wright0@mortys.com', '(514) 555-3000', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2024-12-15', 'pending_invite'),
(46, NULL, 'Michael', 'Carter', 'michael.carter1@mortys.com', '(514) 555-3001', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2025-01-21', 'pending_invite'),
(47, NULL, 'Brian', 'Wright', 'brian.wright2@mortys.com', '(514) 555-3002', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":false,"practical":true}}', 'active', '2025-01-03', 'pending_invite'),
(48, NULL, 'Edward', 'Williams', 'edward.williams3@mortys.com', '(514) 555-3003', NULL, '{"auto":{"theory":true,"practical":false}}', 'active', '2025-01-14', 'pending_invite'),
(49, NULL, 'Edward', 'Wilson', 'edward.wilson4@mortys.com', '(514) 555-3004', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":false}}', 'active', '2025-03-15', 'pending_invite'),
(50, NULL, 'David', 'King', 'david.king5@mortys.com', '(514) 555-3005', NULL, '{"auto":{"theory":false,"practical":false},"moto":{"theory":true,"practical":false},"scooter":{"theory":true,"practical":true}}', 'active', '2025-02-14', 'pending_invite'),
(51, NULL, 'Jacob', 'Rodriguez', 'jacob.rodriguez6@mortys.com', '(514) 555-3006', NULL, '{"auto":{"theory":false,"practical":false}}', 'active', '2025-02-04', 'pending_invite'),
(52, NULL, 'Sarah', 'Wilson', 'sarah.wilson7@mortys.com', '(514) 555-3007', NULL, '{"auto":{"theory":true,"practical":false},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2024-12-09', 'pending_invite'),
(53, NULL, 'Donna', 'Martinez', 'donna.martinez8@mortys.com', '(514) 555-3008', NULL, '{"auto":{"theory":false,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2025-05-09', 'pending_invite'),
(54, NULL, 'Edward', 'Walker', 'edward.walker9@mortys.com', '(514) 555-3009', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":false,"practical":true}}', 'active', '2025-05-12', 'pending_invite'),
(55, NULL, 'Jessica', 'Hernandez', 'jessica.hernandez10@mortys.com', '(514) 555-3010', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2025-04-13', 'pending_invite'),
(56, NULL, 'Kimberly', 'Ramirez', 'kimberly.ramirez11@mortys.com', '(514) 555-3011', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2025-02-22', 'pending_invite'),
(57, NULL, 'Kimberly', 'Brown', 'kimberly.brown12@mortys.com', '(514) 555-3012', NULL, '{"auto":{"theory":true,"practical":false},"moto":{"theory":false,"practical":true},"scooter":{"theory":false,"practical":true}}', 'active', '2024-11-29', 'pending_invite'),
(58, NULL, 'Joseph', 'Rodriguez', 'joseph.rodriguez13@mortys.com', '(514) 555-3013', NULL, '{"auto":{"theory":true,"practical":false},"moto":{"theory":true,"practical":true}}', 'active', '2025-03-01', 'pending_invite'),
(59, NULL, 'William', 'Martinez', 'william.martinez14@mortys.com', '(514) 555-3014', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2025-01-11', 'pending_invite'),
(60, NULL, 'Jason', 'Smith', 'jason.smith0@mortys.com', '(514) 555-3000', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2024-12-16', 'pending_invite'),
(61, NULL, 'Joseph', 'Lopez', 'joseph.lopez1@mortys.com', '(514) 555-3001', NULL, '{"auto":{"theory":false,"practical":true}}', 'active', '2025-01-31', 'pending_invite'),
(62, NULL, 'Timothy', 'Taylor', 'timothy.taylor2@mortys.com', '(514) 555-3002', NULL, '{"auto":{"theory":false,"practical":true},"moto":{"theory":false,"practical":true}}', 'active', '2024-12-09', 'pending_invite'),
(63, NULL, 'William', 'Robinson', 'william.robinson3@mortys.com', '(514) 555-3003', NULL, '{"auto":{"theory":false,"practical":true}}', 'active', '2025-03-26', 'pending_invite'),
(64, NULL, 'Timothy', 'Nguyen', 'timothy.nguyen4@mortys.com', '(514) 555-3004', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":false}}', 'active', '2024-11-30', 'pending_invite'),
(65, NULL, 'Mark', 'Lewis', 'mark.lewis5@mortys.com', '(514) 555-3005', NULL, '{"auto":{"theory":true,"practical":false},"moto":{"theory":true,"practical":true},"scooter":{"theory":false,"practical":true}}', 'active', '2025-03-03', 'pending_invite'),
(66, NULL, 'Joshua', 'Wilson', 'joshua.wilson6@mortys.com', '(514) 555-3006', NULL, '{"auto":{"theory":false,"practical":false}}', 'active', '2025-01-18', 'pending_invite'),
(67, NULL, 'Kenneth', 'Allen', 'kenneth.allen7@mortys.com', '(514) 555-3007', NULL, '{"auto":{"theory":true,"practical":false},"moto":{"theory":true,"practical":true}}', 'active', '2024-12-23', 'pending_invite'),
(68, NULL, 'John', 'Wright', 'john.wright8@mortys.com', '(514) 555-3008', NULL, '{"auto":{"theory":false,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2025-05-22', 'pending_invite'),
(69, NULL, 'Mark', 'Hall', 'mark.hall9@mortys.com', '(514) 555-3009', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2024-11-30', 'pending_invite'),
(70, NULL, 'Ashley', 'Clark', 'ashley.clark10@mortys.com', '(514) 555-3010', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2025-04-13', 'pending_invite'),
(71, NULL, 'Andrew', 'Gonzalez', 'andrew.gonzalez11@mortys.com', '(514) 555-3011', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":false,"practical":false}}', 'active', '2025-05-08', 'pending_invite'),
(72, NULL, 'Donna', 'Martin', 'donna.martin12@mortys.com', '(514) 555-3012', NULL, '{"auto":{"theory":true,"practical":false}}', 'active', '2025-02-03', 'pending_invite'),
(73, NULL, 'John', 'Hall', 'john.hall13@mortys.com', '(514) 555-3013', NULL, '{"auto":{"theory":true,"practical":false}}', 'active', '2025-03-20', 'pending_invite'),
(74, NULL, 'James', 'Carter', 'james.carter14@mortys.com', '(514) 555-3014', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2024-11-26', 'pending_invite'),
(75, NULL, 'Michael', 'Lee', 'michael.lee0@mortys.com', '(514) 555-3000', NULL, '{"auto":{"theory":false,"practical":false}}', 'active', '2025-05-23', 'pending_invite'),
(76, NULL, 'Mark', 'Green', 'mark.green1@mortys.com', '(514) 555-3001', NULL, '{"auto":{"theory":false,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2025-01-31', 'pending_invite'),
(77, NULL, 'Donna', 'Rodriguez', 'donna.rodriguez2@mortys.com', '(514) 555-3002', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2025-01-31', 'pending_invite'),
(78, NULL, 'Kenneth', 'Williams', 'kenneth.williams3@mortys.com', '(514) 555-3003', NULL, '{"auto":{"theory":true,"practical":false},"moto":{"theory":false,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2025-02-27', 'pending_invite'),
(79, NULL, 'Lisa', 'Williams', 'lisa.williams4@mortys.com', '(514) 555-3004', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2025-01-14', 'pending_invite'),
(80, NULL, 'James', 'Hernandez', 'james.hernandez5@mortys.com', '(514) 555-3005', NULL, '{"auto":{"theory":false,"practical":false},"moto":{"theory":true,"practical":true}}', 'active', '2025-05-23', 'pending_invite'),
(81, NULL, 'Margaret', 'Clark', 'margaret.clark6@mortys.com', '(514) 555-3006', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2025-01-13', 'pending_invite'),
(82, NULL, 'John', 'Torres', 'john.torres7@mortys.com', '(514) 555-3007', NULL, '{"auto":{"theory":false,"practical":true},"moto":{"theory":true,"practical":false},"scooter":{"theory":true,"practical":true}}', 'active', '2025-02-04', 'pending_invite'),
(83, NULL, 'Susan', 'Smith', 'susan.smith8@mortys.com', '(514) 555-3008', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":false}}', 'active', '2025-05-24', 'pending_invite'),
(84, NULL, 'Linda', 'Sanchez', 'linda.sanchez9@mortys.com', '(514) 555-3009', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":false,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2025-03-16', 'pending_invite'),
(85, NULL, 'Kenneth', 'Miller', 'kenneth.miller10@mortys.com', '(514) 555-3010', NULL, '{"auto":{"theory":false,"practical":true}}', 'active', '2024-11-26', 'pending_invite'),
(86, NULL, 'Kathleen', 'Allen', 'kathleen.allen11@mortys.com', '(514) 555-3011', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2025-01-04', 'pending_invite'),
(87, NULL, 'Sarah', 'Hernandez', 'sarah.hernandez12@mortys.com', '(514) 555-3012', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":false}}', 'active', '2024-12-29', 'pending_invite'),
(88, NULL, 'Michael', 'Rodriguez', 'michael.rodriguez13@mortys.com', '(514) 555-3013', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2025-01-06', 'pending_invite'),
(89, NULL, 'Ashley', 'Johnson', 'ashley.johnson14@mortys.com', '(514) 555-3014', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2024-12-04', 'pending_invite'),
(90, NULL, 'James', 'Smith', 'james.smith@mortys.com', '(514) 555-3000', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2023-06-01', 'pending_invite'),
(91, NULL, 'Mary', 'Johnson', 'mary.johnson@mortys.com', '(514) 555-3001', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true},"scooter":{"theory":true,"practical":true}}', 'active', '2023-06-01', 'pending_invite'),
(92, NULL, 'John', 'Williams', 'john.williams@mortys.com', '(514) 555-3002', NULL, '{"auto":{"theory":true,"practical":true},"moto":{"theory":true,"practical":true}}', 'active', '2023-06-01', 'pending_invite'),
(93, NULL, 'Patricia', 'Brown', 'patricia.brown@mortys.com', '(514) 555-3003', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2023-06-01', 'pending_invite'),
(94, NULL, 'Robert', 'Jones', 'robert.jones@mortys.com', '(514) 555-3004', NULL, '{"auto":{"theory":true,"practical":true}}', 'active', '2023-06-01', 'pending_invite')
ON CONFLICT (email) DO NOTHING;

-- Reset sequence
SELECT setval('instructors_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM instructors), false);
