-- Vehicles Export (127 records)
-- Run this in production database console

INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (1, 'Toyota', 'Corolla', 2025, 'ABC123', 'auto', 'active', '');
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (6, 'Toyota', 'Aqua', 2025, 'CAD-2127', 'auto', 'active', '');
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (9, 'Chevrolet', 'Cruze', 2019, 'XZZ-6695', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (10, 'Nissan', 'Focus', 2022, 'FPS-8538', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (11, 'Mazda', 'Mazda3', 2021, 'CLE-1230', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (12, 'Ford', 'Sentra', 2019, 'VBP-6288', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (13, 'Toyota', 'Forte', 2020, 'YRW-8324', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (14, 'Honda', 'Ninja 650', 2021, 'NMN-6432', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (15, 'Harley-Davidson', 'Ninja 650', 2024, 'ZBS-2240', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (16, 'Yamaha', 'PCX150', 2018, 'YCR-4216', 'scooter', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (17, 'Honda', 'Elantra', 2024, 'QNY-9805', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (18, 'Ford', 'Sentra', 2021, 'ZIF-3289', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (19, 'Chevrolet', 'Forte', 2020, 'VRC-7936', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (20, 'Toyota', 'Cruze', 2019, 'DPG-6143', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (21, 'Nissan', 'Mazda3', 2024, 'CSA-6828', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (22, 'Suzuki', 'Ninja 650', 2024, 'NPK-2117', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (23, 'Harley-Davidson', 'YZF-R6', 2021, 'DGV-2627', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (24, 'Kymco', 'PCX150', 2018, 'FKD-4192', 'scooter', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (25, 'Mazda', 'Cruze', 2022, 'GCZ-6101', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (26, 'Hyundai', 'Elantra', 2020, 'RPE-1964', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (27, 'Hyundai', 'Corolla', 2018, 'NCY-8432', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (28, 'Mazda', 'Mazda3', 2021, 'QOS-8279', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (29, 'Chevrolet', 'Mazda3', 2019, 'ZOC-7086', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (30, 'Yamaha', 'YZF-R6', 2020, 'LNP-4655', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (31, 'Suzuki', 'YZF-R6', 2019, 'RLU-4525', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (32, 'Honda', 'Like 150', 2021, 'RYD-3620', 'scooter', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (33, 'Nissan', 'Forte', 2023, 'DOH-2877', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (34, 'Ford', 'Cruze', 2019, 'GBE-8386', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (35, 'Nissan', 'Mazda3', 2020, 'NPH-3654', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (36, 'Hyundai', 'Corolla', 2021, 'DKJ-3426', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (37, 'Kia', 'Forte', 2022, 'ZBH-8806', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (38, 'Chevrolet', 'Mazda3', 2018, 'JSH-6134', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (39, 'Suzuki', 'YZF-R6', 2021, 'RAW-1650', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (40, 'Honda', 'CBR600', 2019, 'ZCP-9897', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (41, 'Yamaha', 'Primavera', 2020, 'MWT-5319', 'scooter', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (42, 'Kia', 'Corolla', 2022, 'OLL-1404', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (43, 'Toyota', 'Elantra', 2019, 'TBJ-2801', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (44, 'Kia', 'Civic', 2022, 'JCZ-8434', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (45, 'Ford', 'Mazda3', 2022, 'DDW-9281', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (46, 'Mazda', 'Elantra', 2024, 'FNY-3555', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (47, 'Honda', 'Ninja 650', 2018, 'BIA-6781', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (48, 'Harley-Davidson', 'GSX-R750', 2020, 'UAL-4748', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (49, 'Yamaha', 'Primavera', 2020, 'LMZ-5049', 'scooter', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (50, 'Ford', 'Cruze', 2021, 'OZT-3090', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (51, 'Hyundai', 'Mazda3', 2020, 'QNY-1212', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (52, 'Hyundai', 'Sentra', 2020, 'GVE-6696', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (53, 'Honda', 'Civic', 2018, 'RID-6913', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (54, 'Mazda', 'Cruze', 2023, 'XLX-6936', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (55, 'Suzuki', 'CBR600', 2023, 'LIH-3564', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (56, 'Yamaha', 'CBR600', 2020, 'FGT-2490', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (57, 'Kymco', 'Primavera', 2023, 'GOF-9042', 'scooter', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (58, 'Toyota', 'Focus', 2022, 'QDF-3973', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (59, 'Honda', 'Forte', 2018, 'QFH-3500', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (60, 'Kia', 'Cruze', 2020, 'IFM-9456', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (61, 'Chevrolet', 'Forte', 2024, 'PBB-8462', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (62, 'Mazda', 'Elantra', 2024, 'EMX-2319', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (63, 'Honda', 'Mazda3', 2022, 'ULH-8898', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (64, 'Kawasaki', 'Ninja 650', 2020, 'JUW-7856', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (65, 'Honda', 'GSX-R750', 2022, 'FZP-6506', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (66, 'Kymco', 'Liberty', 2023, 'SVN-7877', 'scooter', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (67, 'Chevrolet', 'Sentra', 2023, 'OAV-4318', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (68, 'Kia', 'Civic', 2022, 'WKR-3735', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (69, 'Honda', 'Focus', 2023, 'UDR-3967', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (70, 'Ford', 'Civic', 2018, 'LRM-9150', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (71, 'Kia', 'Focus', 2020, 'HCT-1005', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (72, 'Suzuki', 'Street 750', 2022, 'JEC-4578', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (73, 'Suzuki', 'Ninja 650', 2023, 'NLV-9768', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (74, 'Honda', 'PCX150', 2020, 'CAU-5500', 'scooter', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (75, 'Toyota', 'Cruze', 2021, 'NWB-9150', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (76, 'Ford', 'Cruze', 2018, 'UPE-5138', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (77, 'Kia', 'Cruze', 2024, 'WXC-2188', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (78, 'Toyota', 'Cruze', 2021, 'EIK-2525', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (79, 'Chevrolet', 'Sentra', 2023, 'CWM-7102', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (80, 'Suzuki', 'GSX-R750', 2021, 'HQD-5107', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (81, 'Suzuki', 'Ninja 650', 2023, 'SCS-4312', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (82, 'Kymco', 'Liberty', 2022, 'XDF-5877', 'scooter', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (83, 'Chevrolet', 'Mazda3', 2018, 'MBM-7043', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (84, 'Kia', 'Civic', 2018, 'LJO-1392', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (85, 'Honda', 'Corolla', 2019, 'OPA-8008', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (86, 'Hyundai', 'Cruze', 2019, 'NVM-5070', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (87, 'Mazda', 'Corolla', 2024, 'BUU-5048', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (88, 'Mazda', 'Corolla', 2023, 'RJI-3517', 'auto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (89, 'Suzuki', 'Street 750', 2024, 'FLY-1228', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (90, 'Kawasaki', 'GSX-R750', 2019, 'WKJ-2975', 'moto', 'active', NULL);
INSERT INTO vehicles (id, make, model, year, license_plate, vehicle_type, status, notes) VALUES (91, 'Vespa', 'Like 150', 2020, 'BQU-2407', 'scooter', 'active', NULL);

-- Note: More vehicles exist in the database. Query remaining with:
-- SELECT * FROM vehicles WHERE id > 91;

-- Reset sequence
SELECT setval('vehicles_id_seq', (SELECT MAX(id) FROM vehicles));
